version: '3'

services:
  # 单一容器服务（前后端一体化）
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/config.json:/app/config.json
    networks:
      - subtitle-network

networks:
  subtitle-network:
    driver: bridge